"""Local registry of projects generated by this program.

We don't want the home screen to show *every* CapCut draft — only the ones this
app created — and we want to remember the exact settings used, so a project can
be duplicated and tweaked. This stores a small JSON in the OS app-data dir.
"""
from __future__ import annotations

import json
import os
import sys
import threading
import time
import uuid
from pathlib import Path


def app_data_dir() -> Path:
    if sys.platform == "darwin":
        base = Path.home() / "Library/Application Support/CapCutAuto"
    elif sys.platform == "win32":
        base = Path(os.environ.get("APPDATA") or str(Path.home())) / "CapCutAuto"
    else:
        base = Path.home() / ".config/capcut-auto"
    base.mkdir(parents=True, exist_ok=True)
    return base


_REGISTRY_PATH = app_data_dir() / "projects.json"
_LOCK = threading.Lock()


def _load() -> list[dict]:
    if not _REGISTRY_PATH.exists():
        return []
    try:
        data = json.loads(_REGISTRY_PATH.read_text())
        return data.get("projects", []) if isinstance(data, dict) else []
    except (json.JSONDecodeError, OSError):
        return []


def _save(projects: list[dict]) -> None:
    tmp = _REGISTRY_PATH.with_suffix(".json.tmp")
    tmp.write_text(json.dumps({"projects": projects}, ensure_ascii=False, indent=2))
    tmp.replace(_REGISTRY_PATH)


def add_project(name: str, result_path: str, settings: dict,
                report_path: str | None = None) -> dict:
    """Record a freshly generated project. `settings` is the full request dict
    so the project can later be duplicated with the same options;
    `report_path` points to the AI decision report."""
    record = {
        "id": uuid.uuid4().hex[:12],
        "name": name,
        "result_path": result_path,
        "report_path": report_path,
        "created_at": time.time(),
        "settings": settings,
    }
    with _LOCK:
        projects = _load()
        projects.insert(0, record)   # newest first
        _save(projects)
    return record


def list_projects() -> list[dict]:
    with _LOCK:
        projects = _load()
    # annotate whether the draft folder still exists on disk
    for p in projects:
        rp = p.get("result_path")
        p["exists"] = bool(rp and Path(rp).exists())
    return projects


def get_project(project_id: str) -> dict | None:
    with _LOCK:
        for p in _load():
            if p["id"] == project_id:
                return p
    return None


def remove_project(project_id: str) -> bool:
    """Remove from the registry (does NOT delete the CapCut draft folder)."""
    with _LOCK:
        projects = _load()
        new = [p for p in projects if p["id"] != project_id]
        if len(new) == len(projects):
            return False
        _save(new)
    return True
